Repository WEB4YOU-BE/P007-TenBoomgaerde, pull requests merged in 2023-09, with the labels that each got.

#27 Showing and adding rooms
  app/_Jens/dashboard/zalen/@modal/(.)add/page.tsx
  app/_Jens/dashboard/zalen/@modal/default.tsx
  app/_Jens/dashboard/zalen/layout.tsx
  app/_Tiebe/dashboard/layout.tsx
  app/_Tiebe/dashboard/page.tsx
  app/_Tiebe/dashboard/producten/[productId]/page.tsx
  app/_Tiebe/dashboard/producten/categorien/[categorieId]/page.tsx
  app/_Tiebe/dashboard/producten/categorien/page.tsx
  app/_Tiebe/dashboard/producten/page.tsx
  app/_Tiebe/dashboard/settings/page.tsx
  app/_Tiebe/dashboard/users/[userId]/page.tsx
  app/_Tiebe/dashboard/users/page.tsx
  app/_Tiebe/dashboard/zalen/[zaalId]/[blokId]/page.tsx
  app/_Tiebe/dashboard/zalen/[zaalId]/page.tsx
  app/_Tiebe/dashboard/zalen/page.tsx
  app/dashboard/zalen/@modal/(.)add/page.tsx
  app/dashboard/zalen/add/page.tsx
  components/business/rooms/add-room-form.tsx
  components/business/rooms/rooms-table.tsx
Labels: enhancement

#29 Producttable and categorytable filled with data from db
  app/dashboard/layout.tsx
  app/dashboard/producten/categorien/page.tsx
  app/dashboard/producten/page.tsx
  components/business/categories/categories-table.tsx
  components/business/categories/category-record-index.tsx
  components/business/products/product-record-index.tsx
  components/business/products/products-table.tsx
  components/navigation/navigation-sidebar-link.tsx
  components/navigation/navigation-sidebar.tsx
  components/ui/button.tsx
  lib/database.types.ts
Labels: bug

#30 Add products and categories
  app/dashboard/producten/add/page.tsx
  app/dashboard/producten/categorien/add/page.tsx
  app/dashboard/producten/categorien/page.tsx
  app/dashboard/producten/page.tsx
  components/business/categories/add-category-form.tsx
  components/business/products/add-product-form.tsx
  package-lock.json
Labels: enhancement

#31 Products and rooms on the www
  app/(www)/layout.tsx
  app/(www)/prijzen/page.tsx
Labels: enhancement

#32 Cleanup for all dashboard pages.
  app/(www)/page.tsx
  app/(www)/reserveren/page.tsx
  app/dashboard/layout.tsx
  app/dashboard/producten/categorieen/add/page.tsx
  app/dashboard/producten/categorieen/page.tsx
  app/dashboard/producten/page.tsx
  app/dashboard/zalen/add/page.tsx
  app/dashboard/zalen/page.tsx
  components/authentication/navigation-sidebar-authentication.tsx
  components/business/categories/add-category-form.tsx
  components/business/categories/categories-table.tsx
  components/business/categories/category-record-index.tsx
  components/business/products/product-record-index.tsx
  components/business/products/products-table.tsx
  components/business/rooms/add-room-form.tsx
  components/business/rooms/room-record-index.tsx
  components/business/rooms/rooms-table.tsx
  components/navigation/navigation-header.tsx
  components/navigation/navigation-sidebar.tsx
  components/ui/button.tsx
  components/ui/www/Footer.tsx
  package-lock.json
  package.json
Labels: enhancement

#33 Reservationproces
  app/(www)/bevestiging/page.tsx
  app/(www)/reserveren/[roomId]/[blokId]/overview/page.tsx
  app/(www)/reserveren/[roomId]/[blokId]/page.tsx
  app/(www)/reserveren/[roomId]/page.tsx
  app/(www)/reserveren/layout.tsx
  app/(www)/reserveren/page.tsx
  app/dashboard/agenda/page.tsx
  app/klant/layout.tsx
  components/Calendar/add-reservation-form.tsx
  components/Calendar/calendar.tsx
  components/Calendar/select-calendar-item.tsx
  components/Calendar/select-calendar.tsx
  components/business/reservations/week-calendar.tsx
  components/ui/Dropdown-menu.tsx
  components/ui/Select.tsx
  components/ui/www/Calender.tsx
  package-lock.json
  package.json
Labels: enhancement

#35 Small things
  app/(www)/page.tsx
  app/(www)/prijzen/page.tsx
  app/not-found.tsx
  components/Calendar/calendar.tsx
Labels: enhancement

#37 Splitting the logic for both types of users.
  app/dashboard/layout.tsx
  components/authentication/admin-component-protection.tsx
  components/authentication/admin-route-protection.tsx
  components/authentication/navigation-header-authentication.tsx
  lib/database.types.ts
  package-lock.json
Labels: enhancement

#38 Code clean-up
  app/(www)/layout.tsx
  app/(www)/prijzen/page.tsx
  app/_Jens/dashboard/zalen/@modal/(.)add/page.tsx
  app/_Jens/dashboard/zalen/@modal/default.tsx
  app/_Jens/dashboard/zalen/layout.tsx
  app/_Tiebe/dashboard/layout.tsx
  app/_Tiebe/dashboard/page.tsx
  app/_Tiebe/dashboard/producten/[productId]/page.tsx
  app/_Tiebe/dashboard/producten/categorien/[categorieId]/page.tsx
  app/_Tiebe/dashboard/producten/categorien/page.tsx
  app/_Tiebe/dashboard/producten/page.tsx
  app/_Tiebe/dashboard/settings/page.tsx
  app/_Tiebe/dashboard/users/[userId]/page.tsx
  app/_Tiebe/dashboard/users/page.tsx
  app/_Tiebe/dashboard/zalen/[zaalId]/[blokId]/page.tsx
  app/_Tiebe/dashboard/zalen/[zaalId]/page.tsx
  app/_Tiebe/dashboard/zalen/page.tsx
  app/_examples/client-component/page.tsx
  app/_examples/route-handler/route.ts
  app/_examples/server-action/page.tsx
  app/_examples/server-component/page.tsx
  app/favicon.ico
  components/navigation/navigation-footer.tsx
  components/ui/dashboard/CategorieDialog.tsx
  components/ui/dashboard/Navigation.tsx
  components/ui/dashboard/ProductAside.tsx
  components/ui/dashboard/ZaalAside.tsx
  components/ui/klant/Navigation.tsx
  components/ui/www/Footer.tsx
  package-lock.json
Labels: duplicate, enhancement
