Repository WEB4YOU-BE/P007-TenBoomgaerde, pull requests merged in 2023-12, with the labels that each got.

#50 Last things before online
  app/(www)/page.tsx
  app/(www)/prijzen/page.tsx
  app/dashboard/analyses/page.tsx
  app/dashboard/organisaties/[organisationId]/page.tsx
  app/dashboard/organisaties/add/page.tsx
  app/dashboard/page.tsx
  app/dashboard/producten/[productId]/page.tsx
  app/dashboard/producten/add/page.tsx
  app/dashboard/producten/categorieen/[categoryId]/page.tsx
  app/dashboard/producten/categorieen/add/page.tsx
  app/dashboard/zalen/[roomId]/page.tsx
  app/dashboard/zalen/add/page.tsx
  app/dashboard/zalen/blokken/[blokId]/page.tsx
  app/dashboard/zalen/blokken/add/page.tsx
  components/authentication/navigation-header-authentication.tsx
  components/business/categories/add-category-form.tsx
  components/business/categories/categories-table.tsx
  components/business/categories/change-category-form.tsx
  components/business/organizations/add-organization-form.tsx
  components/business/organizations/change-organization-form.tsx
  components/business/organizations/organization-record-index.tsx
  components/business/products/add-product-form.tsx
  components/business/products/change-product-form.tsx
  components/business/reservations/bloks/add-blok-form.tsx
  components/business/reservations/bloks/change-blok-form.tsx
  components/business/reservations/info-reservation-form.tsx
  components/business/rooms/add-room-form.tsx
  components/business/rooms/change-room-form.tsx
  components/business/users/info-users-form.tsx
  components/business/users/user-record-index.tsx
  components/business/users/users-table.tsx
  components/navigation/navigation-footer.tsx
  components/navigation/navigation-header.tsx
  components/navigation/navigation-sidebar.tsx
  components/navigation/responsive-header.tsx
  components/navigation/responsive-sidebar.tsx
  lib/database.types.ts
  public/documents/Reglement_vergaderzalen_Ten_Boomgaerde_vzw.pdf
Labels: enhancement

#58 See commits
  app/(www)/page.tsx
  app/(www)/reserveren/page.tsx
  components/navigation/navigation-footer.tsx
  components/navigation/navigation-header-link.tsx
  components/navigation/navigation-header.tsx
  components/reservations/ReservationForm.tsx
  components/ui/klant/Reservation.tsx
  package-lock.json
  package.json
Labels: bug, enhancement

#60 Reservation-form partially completed
  app/(www)/reserveren/page.tsx
  components/business/rooms/change-room-form.tsx
  components/business/rooms/room-record-index.tsx
  components/business/rooms/rooms-table.tsx
  components/reservations/ReservationForm.tsx
  components/ui/checkbox.tsx
  lib/database.types.ts
  package-lock.json
  package.json
Labels: enhancement, wontfix

#62 Fixed reservations issues when having no reservations in the system yet.
  app/(www)/reserveren-tiebe/[roomId]/[blokId]/overview/page.tsx
  app/(www)/reserveren-tiebe/[roomId]/[blokId]/page.tsx
  app/(www)/reserveren-tiebe/[roomId]/page.tsx
  app/(www)/reserveren-tiebe/layout.tsx
  app/(www)/reserveren-tiebe/page.tsx
  app/(www)/reserveren/page.tsx
  components/reservations/ReservationForm.tsx
Labels: bug, enhancement

#64 Fixed reservations issues when having no reservations in the system yet.
  app/(www)/reserveren-tiebe/[roomId]/[blokId]/overview/page.tsx
  app/(www)/reserveren-tiebe/[roomId]/[blokId]/page.tsx
  app/(www)/reserveren-tiebe/[roomId]/page.tsx
  app/(www)/reserveren-tiebe/layout.tsx
  app/(www)/reserveren-tiebe/page.tsx
  app/(www)/reserveren/page.tsx
  components/reservations/ReservationForm.tsx
Labels: bug, enhancement

#65 V1.0.1
  app/(www)/reserveren-tiebe/[roomId]/[blokId]/overview/page.tsx
  app/(www)/reserveren-tiebe/[roomId]/[blokId]/page.tsx
  app/(www)/reserveren-tiebe/[roomId]/page.tsx
  app/(www)/reserveren-tiebe/layout.tsx
  app/(www)/reserveren-tiebe/page.tsx
  app/(www)/reserveren/page.tsx
  components/reservations/ReservationForm.tsx
Labels: enhancement

#66 Fixed the redirect URL on sign up
  app/(www)/bevestiging/page.tsx
  app/(www)/test/page.tsx
  app/auth/callback/route.ts
  components/test.tsx
Labels: enhancement

#67 v1.0.2
  app/(www)/bevestiging/page.tsx
  app/(www)/test/page.tsx
  app/auth/callback/route.ts
  components/test.tsx
Labels: enhancement

#70 V1.0.3
  app/(www)/reserveren/page.tsx
  components/reservations/ReservationForm.tsx
Labels: enhancement

#72 Fixed date on dialog
  components/reservations/ReservationForm.tsx
Labels: bug

#73 V1.0.4
  components/reservations/ReservationForm.tsx
Labels: bug, enhancement
